# Generated by Django 3.0.8 on 2020-07-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djproduct', '0005_auto_20200727_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='label',
            field=models.CharField(blank=True, choices=[('Hot', 'Hot'), ('Sale', 'Sale'), ('New', 'New')], max_length=100),
        ),
    ]
