# Generated by Django 3.0.8 on 2020-07-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djproduct', '0006_product_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='min_amount',
        ),
        migrations.AddField(
            model_name='product',
            name='discounted_price',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
