# Generated by Django 3.0.8 on 2020-07-29 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djproduct', '0010_auto_20200729_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_reviews',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Read', 'Read'), ('True', 'True')], default='New', max_length=100),
        ),
    ]
