# Generated by Django 3.0.8 on 2020-08-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djproduct', '0012_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='items_in_stock',
            field=models.IntegerField(default=0),
        ),
    ]
