# Generated by Django 3.0.8 on 2020-08-03 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djproduct', '0014_order_orderproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='discounted_price',
        ),
    ]
