# Generated by Django 3.0.8 on 2020-08-03 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djproduct', '0015_remove_orderproduct_discounted_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ip',
            new_name='ip_address',
        ),
    ]
