# Generated by Django 3.0.8 on 2020-08-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djproduct', '0019_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
