# Generated by Django 3.0.8 on 2020-08-10 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djproduct', '0020_wishlist_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
