# Generated by Django 3.0.8 on 2020-08-10 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djproduct', '0022_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
