# Generated by Django 3.0.8 on 2020-08-14 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djproduct', '0029_wishlist_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='cart',
        ),
    ]
