# Generated by Django 3.0.8 on 2020-07-27 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0003_contact_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_message',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
