# Generated by Django 3.0.8 on 2020-08-16 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0007_newsletter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
