# Generated by Django 3.0.8 on 2020-07-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='zip_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
